title: 리보이스
author: inseop kim
email: revoice_studio@naver.com
description: > # this means to ignore newlines until "show_exerpts:"
  음성 컨텐츠 개발 | AI 스피커 | 음성 개발 | SKT nugu | amazon alexa | samsung bixby
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 리보이스 스튜디오
  tagline: Developer. VUX
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: revoice-studio
  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github: revoiceStudio
    revoice: revoice
    #linkedIn: in/thelehhman
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
